sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: hxsnn
    password: 123456

  alioss:
   endpoint: oss-cn-beijing.aliyuncs.com
   access-key-id: LTAI5tCE5BN4pqAZ6FzzLdBu
   access-key-secret: wxbeRm3BUlcNnRtKF2IJJePuCTccpr
   bucket-name: sky-take-out-zhangboooooo
